# Generated by Django 5.0.6 on 2024-07-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHospitalApp', '0002_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=65)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=350)),
            ],
        ),
    ]
